version: '3.8'

services:
  hello-world-container:
    image: hello-world:latest
    deploy:
      replicas: 5
    restart: always

  spring-boot-app:
    image: ultra-app:1.0
    environment:
      - DEVOPS=Bam-ba-lejla
    ports:
      - "8081:8081"
    depends_on:
      - database
    restart: always

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:./src/main/resources/sql/init.sql
    restart: always