apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "sampledb"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "userpassword"
        volumeMounts:
        - name: init-sql-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql-volume
        configMap:
          name: database-config
